import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { initializeApollo } from '@graphqlClient/client'
import { GetAuthorDocument, useGetAuthorQuery } from '@gTypes/graphql-generated'

const Home: NextPage = () => {
	const { data, loading } = useGetAuthorQuery({ variables: { id: "752" } })

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h2>Look in <code>getServerSideProps</code></h2>
				<p>and change the id of the query to play with the cache</p>
				<div>{loading ? "LOADING DATA" : data?.getAuthor.name}</div>
			</main>
		</div>
	)
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const apolloClient = initializeApollo();
	await apolloClient.query({ query: GetAuthorDocument, variables: { id: "752" } })
	return {
		props: {
			initialApolloState: apolloClient.cache.extract(),
		}
	}
}

export default Home
