import { dehydrate, QueryClient } from 'react-query'
import { useGetAuthorQuery } from '@gTypes/graphql-generated'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	const { data, isLoading } = useGetAuthorQuery({ id: "752" })

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h2>Look in <code>getServerSideProps</code></h2>
				<p>and change the id of the query to play with the cache</p>
				<div>{isLoading ? "LOADING DATA" : data?.getAuthor?.name}</div>
			</main>
		</div>
	)
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const queryClient = new QueryClient()

	await queryClient.prefetchQuery(
		useGetAuthorQuery.getKey({ id: "752" }),
		() => useGetAuthorQuery.fetcher({ id: "752" })
	)

	const dehydratedState = dehydrate(queryClient)
	const state = dehydratedState.queries.map(async (query) => {
		const data = await query.state.data
		return { ...query, state: { ...query.state, data } }
	})
	const state2 = { ...dehydratedState, queries: await Promise.all(state) }

	return {
		props: {
			dehydratedState: state2
		}
	}
}

export default Home
